### ISSUE TITLE
No result shows in the Browser

### ISSUE THREAD

**Issue by Karl-Zhuo** [rte-france/grid2viz#20]
Hi
I installed the package and run the command in the windows terminal. There is a page popped out in my browser but results are not presented. You can see the blue menu bar but it is just empty below. I am using the agents_path and env in the original package. Any idea about what is wrong here?

import os
agent_dir = "XXX\Grid2op_learning\Grid2Viz\grid2viz\data\agents"
env_dir = "XXX\Grid2op_learning\Grid2Viz\grid2viz\data\env_conf"
comm="grid2viz --agents_path "+agent_dir+" --env_path "+env_dir+" --port 8050"
os.system(comm)

 * Serving Flask app "grid2viz.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [04/Jun/2020 10:30:17] "GET / HTTP/1.1" 200 -

**Comment by mjothy** [comment]
Hello,

Are the paths that you provide absolute or relative ?

Also, can you try simply running : 
`grid2viz` 
Without any additional args ? It should load the default folders automatically.

Thank you,

Mario

**Comment by marota** [comment]
@Karl-Zhuo do you still have a problem regarding that issue?
