### ISSUE TITLE
agent actions not well printed anymore in hover mode over distance & action graph

### ISSUE THREAD

**Issue by marota** [rte-france/grid2viz#55]
When hovering over the actions tick, we don't get the proper action description anymore

![image](https://user-images.githubusercontent.com/5496312/98712011-087e0b00-2386-11eb-9991-686372eb3c25.png)

**Comment by marota** [comment]
[res_agents.zip](https://github.com/mjothy/grid2viz/files/5545485/res_agents.zip)

@vinault When you go through this scenario and you use ref_agent=do_nothing and study_agent=rl_agnet, you have this problem.  Can you see why ?

**Comment by vinault** [comment]
@marota : did you experience the problem in debug mode ? Either the dash debug tools or any IDE debugger.

For some obscure reason, I can only reproduce it in debug.

**Comment by marota** [comment]
@vinault it does it for me in any mode unfortunately

**Comment by vinault** [comment]
Fixed in 1.0.0.

**Comment by marota** [comment]
@marota for review

**Comment by marota** [comment]
Checked on binder on this scenario and scenario dec_1 with https://mybinder.org/v2/gh/mjothy/grid2viz/grid2op-1.5/?urlpath=git-pull?repo=https://github.com/marota/Grid2viz-dataset-NeurIPS-Robustness%26amp%3Burlpath=tree/../%26amp%3Burlpath=tree/Grid2Viz_demo.ipynb%3Fautodecode
