### ISSUE TITLE
Add Text Directions for user in each tab

### ISSUE THREAD

**Issue by marota** [rte-france/grid2viz#60]
In the blue navbar, we could add some short instructions for the user to guide him in its navigation.
1) " Choose a scenario - click "Open" to study it"
2) " Next, continue to Agent Overview"
3) " Select Timesteps and go to Agent Study "
4) We already have the timestep dropdown list - no need for text for now

![image](https://user-images.githubusercontent.com/5496312/99268841-f7217c80-2825-11eb-9492-0016e74d206d.png)

**Comment by vinault** [comment]
This as been done through the use of a Modal. Seec695cd30.
