### ISSUE TITLE
Unable to load episodes saved during custom training into grid2viz

### ISSUE THREAD

**Issue by mlanden** [rte-france/grid2viz#71]
I wrote a custom training algorithm using grid2op and saved each episode to disc with the EpisodeData class. Now, i am trying to point grid2viz at the folder with the episodes saved, but I'm getting an error 

Custom training script 

        self.env = make_env(env_name)
        self.env.seed(seeds[1])
        tf.random.set_seed(seeds[2])
        self.env_name = env_name
        self.action_list = get_actions(actions_path = self.actions_path)
        self.action_space = self.env.action_space

        self.setup_model()
        self.set_policy()

        episode = self.episode_sync(self.episode.value)
        while not self.episodes_completed.is_set():
            self.env.reset()
            path_save = f"./episodes/{self.experiment_name}"
             episode_data = prepare_episode_data(
                 env = self.env,
                 logger = ConsoleLog(),
                 episode = episode,
                 path_save = path_save
             )

            start_timestep = np.random.randint(1000)
            self.env.fast_forward_chronics(start_timestep)
            max_steps_chronic = self.env.chronics_handler.max_timestep() - start_timestep

            state_obj = self.env.get_obs()
            state = self.convert_state(state_obj)
            next_state = None
            total_reward = 0
            steps = 0
            actions_taken = []
            time_act = 0

            done = False
            start = time.time()
            while not done and steps < max_steps_chronic:
                beg__ = time.time()
                action_distribution, action_idx, action_obj = self.policy.act(state_obj, epsilon = epsilon)
                end__ = time.time()
                time_act += end__ - beg__

                next_state, reward, done, info = self.env.step(action_obj)
                episode_data.incr_store(True, steps, end__ - beg__, float(reward),
                                        self.env._env_modification, action_obj, next_state,
                                        self.env._oppSpace.last_attack, info)

                state_obj = next_state
                next_state = self.convert_state(next_state)
                total_reward += reward
                actions_taken.append(action_idx)
                steps += 1

            end = time.time()

            episode_data.set_meta(self.env, steps, total_reward, None, None)
            episode_data.set_episode_times(self.env, time_act, start, end)
            episode_data.to_disk()

            length = end - start

And the prepare_episode_data method: 

    def prepare_episode_data(env, logger, episode, path_save=None,
                         env_seed=None, max_iter=None):
    time_step = int(0)

    # reset the environment
    env.chronics_handler.tell_id(episode-1)
    # the "-1" above is because the environment will be reset. So it will increase id of 1.

    # set the seed
    if env_seed is not None:
        env.seed(env_seed)

    # handle max_iter
    if max_iter is not None:
        env.chronics_handler.set_max_iter(max_iter)

    # reset it
    obs = env.reset()

    # seed and reset the agent
    # if agent_seed is not None:
    #     agent.seed(agent_seed)
    # agent.reset(obs)

    # compute the size and everything if it needs to be stored
    nb_timestep_max = env.chronics_handler.max_timestep()
    efficient_storing = nb_timestep_max > 0
    nb_timestep_max = max(nb_timestep_max, 0)

    if path_save is None:
        # i don't store anything on drive, so i don't need to store anything on memory
        nb_timestep_max = 0

    disc_lines_templ = np.full(
        (1, env.backend.n_line), fill_value=False, dtype=dt_bool)

    attack_templ = np.full(
        (1, env._oppSpace.action_space.size()), fill_value=0., dtype=dt_float)
    if efficient_storing:
        times = np.full(nb_timestep_max, fill_value=np.NaN, dtype=dt_float)
        rewards = np.full(nb_timestep_max, fill_value=np.NaN, dtype=dt_float)
        actions = np.full((nb_timestep_max, env.action_space.n),
                          fill_value=np.NaN, dtype=dt_float)
        env_actions = np.full(
            (nb_timestep_max, env._helper_action_env.n), fill_value=np.NaN, dtype=dt_float)
        observations = np.full(
            (nb_timestep_max+1, env.observation_space.n), fill_value=np.NaN, dtype=dt_float)
        disc_lines = np.full(
            (nb_timestep_max, env.backend.n_line), fill_value=np.NaN, dtype=dt_bool)
        attack = np.full((nb_timestep_max, env._opponent_action_space.n), fill_value=0., dtype=dt_float)
    else:
        times = np.full(0, fill_value=np.NaN, dtype=dt_float)
        rewards = np.full(0, fill_value=np.NaN, dtype=dt_float)
        actions = np.full((0, env.action_space.n), fill_value=np.NaN, dtype=dt_float)
        env_actions = np.full((0, env._helper_action_env.n), fill_value=np.NaN, dtype=dt_float)
        observations = np.full((0, env.observation_space.n), fill_value=np.NaN, dtype=dt_float)
        disc_lines = np.full((0, env.backend.n_line), fill_value=np.NaN, dtype=dt_bool)
        attack = np.full((0, env._opponent_action_space.n), fill_value=0., dtype=dt_float)

    if path_save is not None:
        # store observation at timestep 0
        if efficient_storing:
            observations[time_step, :] = obs.to_vect()
        else:
            observations = np.concatenate((observations, obs.to_vect().reshape(1, -1)))

    episode = EpisodeData(actions=actions,
                          env_actions=env_actions,
                          observations=observations,
                          rewards=rewards,
                          disc_lines=disc_lines,
                          times=times,
                          observation_space=env.observation_space,
                          action_space=env.action_space,
                          helper_action_env=env._helper_action_env,
                          path_save=path_save,
                          disc_lines_templ=disc_lines_templ,
                          attack_templ=attack_templ,
                          attack=attack,
                          attack_space=env._opponent_action_space,
                          logger=logger,
                          name=env.chronics_handler.get_name(),
                          other_rewards=[])

    episode.set_parameters(env)
    return episode
`

Finally, I run grid2viz with:
python -m grid2viz.main --agents_path=<full path to>/episodes

And I receive this error: 
`
    
```
Traceback (most recent call last):
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\dash\dash.py", line 1007, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "D:\Users\landen2\drl\Grid2Viz\grid2viz\src\episodes\episodes_clbk.py", line 68, in load_scenario_cards
    sorted_scenarios,
  File "D:\Users\landen2\drl\DragonGlass\venv\lib\site-packages\multiprocess\pool.py", line 748, in next
    raise value
ValueError: Not all things are on bus 1
```
`

**Comment by vinault** [comment]
Hi @mlanden, 
this is an error raised by grid2viz when the initial network has "something" connected on a bus different that bus 1, which is something that is not supported for now.
Can you confirm that you are in this situation? 
Many thanks.
Cheers

**Comment by mlanden** [comment]
I guess that is correct, however, I am not sure why this would cause a problem because I am running the chronics from the robustness track of the recent Neurips competition and the starting states should be the same.
