### ISSUE TITLE
Attack Data table returns NAN values for new grid2op versions

### ISSUE THREAD

**Issue by marota** [rte-france/grid2viz#78]
For grid2op version 1.4.0, episode_analytics.attacks_data_table returns Nan values in Attack column (and not boolean values)

For grid2op versions up to 1.3.1 it was working fine
![image](https://user-images.githubusercontent.com/5496312/105836959-432f3100-5fce-11eb-90f6-a5f6ac4a5ef9.png)

**Comment by vinault** [comment]
Bug was found in Grid2Op and will be corrected in Grid2Op 1.5

**Comment by marota** [comment]
@marota for review on binder depuis branch grid2op-1.5
https://mybinder.org/v2/gh/mjothy/grid2viz/grid2op-1.5/?urlpath=git-pull?repo=https://github.com/marota/Grid2viz-dataset-NeurIPS-Robustness%26amp%3Burlpath=tree/../%26amp%3Burlpath=tree/Grid2Viz_demo.ipynb%3Fautodecode

**Comment by marota** [comment]
Indeed Working with Grid2op 1.5.1 now if logs are generated from either 1.3.1  or 1.5.1

![image](https://user-images.githubusercontent.com/5496312/116122525-30f28b00-a6c2-11eb-98f1-f0ca039b660b.png)
