### ISSUE TITLE
More options to analyse the scenario

### ISSUE THREAD

**Issue by jhmenke** [rte-france/grid2viz#8]
In the scenario overview, it is already very nice to see what the generators and loads are doing! 
Right now, i need to add generators and loads into the visualization one by one. A button to add all available generators / loads would be a time saver.

Regarding the grid, i am missing a bit the option to analyse how the grid is doing during the time steps, e.g.:

- seeing the line and transformer loadings (and optionally the absolute flows) of every timestep (analogous to the load plot)
- having them maybe visualized on a grid scheme graphically so i can instantly notice where the issues are in the grid and what generators/loads are close by

This could be helpful to analyze the parts of a grid (especially later in the ieee118) where issues occur most often.

**Comment by marota** [comment]
It is true having the option to display all loads or all productions at once would help.

If you want to look at the flows and grid, this is a representation available in agent study. It depends of the agent and this is going into greater details so for us it really makes sense to study it there.

In scenario overview, you basically want to grab the high level context and confirm that you want to study further the scenario. Maybe a representation of the grid with some statistics could make sense for the referent agent, but this needs more thoughts

**Comment by marota** [comment]
this was completed some time ago
